site_name: Документация для лабораторной работы №2
nav:
  - Home: index.md
  - models.py: models.md
  - views.py: views.md
  - urls.py: urls.md
  - forms.py: forms.md

site_name: My Django Project Documentation
nav:

  - Buy Tour: myapp/buy_tour.md
  - Tour List: myapp/tour_list.md
  - Reserve Tour: myapp/reserve_tour.md